defaults: &defaults
  site_name: IT123
  author: zhangjingqiang
  about_me: http://about.me/zhangjingqiang
  google_analytics: UA-58742812-1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults